# Generated by Django 5.1.4 on 2025-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=1, verbose_name='Old Price'),
            preserve_default=False,
        ),
    ]
