# Generated by Django 5.1.4 on 2025-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
