# Generated by Django 5.1.4 on 2025-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('url_title', models.URLField(max_length=400, verbose_name='Banner URL')),
                ('image', models.ImageField(upload_to='images/site_banner', verbose_name='Banner Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('position', models.CharField(choices=[('home', 'Home page'), ('product_list', 'Product List page'), ('product_details', 'Product Details Page')], max_length=200, verbose_name='Display Position')),
            ],
            options={
                'verbose_name': 'Site Banner',
                'verbose_name_plural': 'Site Banners',
            },
        ),
    ]
