# Generated by Django 5.1.4 on 2025-03-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUS',
        ),
    ]
