# Generated by Django 5.1.4 on 2025-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_rename_contact_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(max_length=400, verbose_name='Users Comments'),
        ),
    ]
